REQUEST:
GET http://localhost:8080/survey
headers: { Authorization: "Bearer " + tokenGoesHere }

RESPONSE:
[
    {
        "id": 1,
        "name": "ankieta",
        "description": "another one2",
        "dueDate": "2021-04-23T18:25:44.000Z"
    },
    {
        "id": 2,
        "name": "ankieta",
        "description": "another one2",
        "dueDate": "2021-04-23T18:25:44.000Z"
    },
    {
        "id": 3,
        "name": "ankieta",
        "description": "another one2",
        "dueDate": "2021-04-23T18:25:44.000Z"
    },
    {
        "id": 4,
        "name": "ankieta",
        "description": "another one2",
        "dueDate": "2021-04-23T18:25:44.000Z"
    },
    {
        "id": 5,
        "name": "ankieta",
        "description": "another one2",
        "dueDate": "2021-04-23T18:25:44.000Z"
    },
    {
        "id": 6,
        "name": "ankieta",
        "description": "another one2",
        "dueDate": "2021-04-23T18:25:44.000Z"
    },
    {
        "id": 7,
        "name": "ankieta",
        "description": "another one2",
        "dueDate": "2021-04-23T18:25:44.000Z"
    },
    {
        "id": 19,
        "name": "ankieta",
        "description": "another one2",
        "dueDate": "2021-04-23T18:25:44.000Z"
    },
    {
        "id": 24,
        "name": "asdf",
        "description": "asdf",
        "dueDate": "2020-11-01T23:00:00.000Z"
    }
]