REQEUST:
PUT http://localhost:8080/user-survey-response/:id

headers: { Authorization: "Bearer " + tokenGoesHere }

RESPONSE:
content-type: application/json
{
    "answers": 
    [
      {
        "questionId": 1,
        "value": "Odpowiedź"
      },
      {
        "questionId": 2,
        "value": "0"
      },
      {
        "questionId": 2,
        "value": "2"
      },
      {
        "questionId": 3,
        "value": "5"
      },
      {
        "questionId": 4,
        "value": "Inna odpowiedź"
      }
    ]
}