POST http://localhost:8080/user-survey-response
content-type: application/json
{
    "user_id": "1",
    "survey_id": "1",
    "answers": 
    [
      {
        "id": "1",
        "type": "text,
        "response": "Odpowiedź"
      },
      {
        "id": "2",
        "type": "multiple_choice",
        "response": "0"
      },
      {
        "id": "2",
        "type": "multiple_choice",
        "response": "2"
      },
      {
        "id": "3",
        "type": "single_choice",
        "response": "1"
      },
      {
        "id": "4",
        "type": "text",
        "response": "Inna odpowiedź"
      },
    ]
}